// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_MusicPlayer

#ifndef _SQUARELINE_PROJECT_MUSICPLAYER_UI_H
#define _SQUARELINE_PROJECT_MUSICPLAYER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void caidanPanelSHOW_Animation(lv_obj_t * TargetObject, int delay);
void HaibaoXuanzhuan_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_background1(lv_event_t * e);
extern lv_obj_t * ui_background1;
void ui_event_background2(lv_event_t * e);
extern lv_obj_t * ui_background2;
void ui_event_BottomPanel(lv_event_t * e);
extern lv_obj_t * ui_BottomPanel;
extern lv_obj_t * ui_MusicTitleLabel;
extern lv_obj_t * ui_MusicArtistLabel;
extern lv_obj_t * ui_MusicLrcLabel;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_MusicTimeLabel1;
extern lv_obj_t * ui_MusicTimeLabel2;
void ui_event_PauseButton(lv_event_t * e);
extern lv_obj_t * ui_PauseButton;
void ui_event_PlayButton(lv_event_t * e);
extern lv_obj_t * ui_PlayButton;
void ui_event_NextButton(lv_event_t * e);
extern lv_obj_t * ui_NextButton;
void ui_event_PlayModeButton(lv_event_t * e);
extern lv_obj_t * ui_PlayModeButton;
void ui_event_VolumeButton(lv_event_t * e);
extern lv_obj_t * ui_VolumeButton;
void ui_event_PrevButton(lv_event_t * e);
extern lv_obj_t * ui_PrevButton;
void ui_event_MidPanel(lv_event_t * e);
extern lv_obj_t * ui_MidPanel;
extern lv_obj_t * ui_jiaopian;
extern lv_obj_t * ui_haibao;
extern lv_obj_t * ui_citou;
extern lv_obj_t * ui_TopPanel;
extern lv_obj_t * ui_Image1;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_caidanPanel;
extern lv_obj_t * ui_PlayListPanel;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_VolumePanel;
void ui_event_VolumeSlider(lv_event_t * e);
extern lv_obj_t * ui_VolumeSlider;
extern lv_obj_t * ui_VolumeLabel;
extern lv_obj_t * ui_VolumeValueLabel;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_zanting1_png);    // assets/zanting1.png
LV_IMG_DECLARE(ui_img_zanting2_png);    // assets/zanting2.png
LV_IMG_DECLARE(ui_img_bofang1_png);    // assets/bofang1.png
LV_IMG_DECLARE(ui_img_bofang2_png);    // assets/bofang2.png
LV_IMG_DECLARE(ui_img_xiyi1_png);    // assets/xiyi1.png
LV_IMG_DECLARE(ui_img_xiyi2_png);    // assets/xiyi2.png
LV_IMG_DECLARE(ui_img_list_loop_png);    // assets/LIST_LOOP.png
LV_IMG_DECLARE(ui_img_yinliang_png);    // assets/yinliang.png
LV_IMG_DECLARE(ui_img_shangyi1_png);    // assets/shangyi1.png
LV_IMG_DECLARE(ui_img_shangyi2_png);    // assets/shangyi2.png
LV_IMG_DECLARE(ui_img_jiaopian_png);    // assets/jiaopian.png
LV_IMG_DECLARE(ui_img_haibao_png);    // assets/haibao.png
LV_IMG_DECLARE(ui_img_citou_png);    // assets/citou.png
LV_IMG_DECLARE(ui_img_fanhui_png);    // assets/fanhui.png
LV_IMG_DECLARE(ui_img_caidan_png);    // assets/caidan.png
LV_IMG_DECLARE(ui_img_random_play_png); // assets/RANDOM_PLAY.png
LV_IMG_DECLARE(ui_img_single_loop_png); // assets/SINGLE_LOOP.png

// FONTS
LV_FONT_DECLARE(ui_font_HONOR_Light12);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
