// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_MusicPlayer

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void PauseClicke(lv_event_t * e);
void PlayClicked(lv_event_t * e);
void NextClicke(lv_event_t * e);
void PlayModeClicked(lv_event_t * e);
void VolumeClicked(lv_event_t * e);
void PrevClicked(lv_event_t * e);
void PlayListButtonClicked(lv_event_t * e);
void VolumeValueChange(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
