// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_MusicPlayer

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_background1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_background1, 240);
    lv_obj_set_height(ui_background1, 170);
    lv_obj_set_x(ui_background1, 0);
    lv_obj_set_y(ui_background1, -1);
    lv_obj_set_align(ui_background1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_background1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_background1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_background1, lv_color_hex(0x0B283D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_background1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_background1, lv_color_hex(0x263D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_background1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_background1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_background1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_background1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_background2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_background2, 240);
    lv_obj_set_height(ui_background2, 170);
    lv_obj_set_align(ui_background2, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_background2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_background2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_background2, lv_color_hex(0x263D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_background2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_background2, lv_color_hex(0x04263E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_background2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_background2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_background2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_background2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BottomPanel, 240);
    lv_obj_set_height(ui_BottomPanel, 130);
    lv_obj_set_align(ui_BottomPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_BottomPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_BottomPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MusicTitleLabel = lv_label_create(ui_BottomPanel);
    lv_obj_set_width(ui_MusicTitleLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_MusicTitleLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_MusicTitleLabel, 0);
    lv_obj_set_y(ui_MusicTitleLabel, -51);
    lv_obj_set_align(ui_MusicTitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicTitleLabel, "心中的日月");
    lv_obj_set_style_text_color(ui_MusicTitleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MusicTitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_MusicTitleLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_MusicTitleLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MusicTitleLabel, &ui_font_HONOR_Light12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MusicArtistLabel = lv_label_create(ui_BottomPanel);
    lv_obj_set_width(ui_MusicArtistLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_MusicArtistLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_MusicArtistLabel, 0);
    lv_obj_set_y(ui_MusicArtistLabel, -36);
    lv_obj_set_align(ui_MusicArtistLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicArtistLabel, "王力宏");
    lv_obj_set_style_text_color(ui_MusicArtistLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MusicArtistLabel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_MusicArtistLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_MusicArtistLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MusicArtistLabel, &ui_font_HONOR_Light12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MusicLrcLabel = lv_label_create(ui_BottomPanel);
    lv_obj_set_width(ui_MusicLrcLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_MusicLrcLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_MusicLrcLabel, 0);
    lv_obj_set_y(ui_MusicLrcLabel, -16);
    lv_obj_set_align(ui_MusicLrcLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicLrcLabel, "你是我心中的日月光芒");
    lv_obj_set_style_text_color(ui_MusicLrcLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MusicLrcLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_MusicLrcLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_MusicLrcLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MusicLrcLabel, &ui_font_HONOR_Light12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_BottomPanel);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 160);
    lv_obj_set_height(ui_Bar1, 2);
    lv_obj_set_x(ui_Bar1, 0);
    lv_obj_set_y(ui_Bar1, 8);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    ui_MusicTimeLabel1 = lv_label_create(ui_BottomPanel);
    lv_obj_set_width(ui_MusicTimeLabel1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_MusicTimeLabel1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_MusicTimeLabel1, -100);
    lv_obj_set_y(ui_MusicTimeLabel1, 8);
    lv_obj_set_align(ui_MusicTimeLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicTimeLabel1, "01:25");
    lv_obj_set_style_text_color(ui_MusicTimeLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MusicTimeLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MusicTimeLabel1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MusicTimeLabel2 = lv_label_create(ui_BottomPanel);
    lv_obj_set_width(ui_MusicTimeLabel2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_MusicTimeLabel2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_MusicTimeLabel2, 100);
    lv_obj_set_y(ui_MusicTimeLabel2, 8);
    lv_obj_set_align(ui_MusicTimeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicTimeLabel2, "01:25");
    lv_obj_set_style_text_color(ui_MusicTimeLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MusicTimeLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MusicTimeLabel2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PauseButton = lv_imgbtn_create(ui_BottomPanel);
    lv_imgbtn_set_src(ui_PauseButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_zanting1_png, NULL);
    lv_imgbtn_set_src(ui_PauseButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_zanting2_png, NULL);
    lv_obj_set_width(ui_PauseButton, 31);
    lv_obj_set_height(ui_PauseButton, 31);
    lv_obj_set_x(ui_PauseButton, 0);
    lv_obj_set_y(ui_PauseButton, 38);
    lv_obj_set_align(ui_PauseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PauseButton, LV_OBJ_FLAG_HIDDEN); /// Flags

    ui_PlayButton = lv_imgbtn_create(ui_BottomPanel);
    lv_imgbtn_set_src(ui_PlayButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_bofang1_png, NULL);
    lv_imgbtn_set_src(ui_PlayButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_bofang2_png, NULL);
    lv_obj_set_width(ui_PlayButton, 31);
    lv_obj_set_height(ui_PlayButton, 31);
    lv_obj_set_x(ui_PlayButton, 0);
    lv_obj_set_y(ui_PlayButton, 38);
    lv_obj_set_align(ui_PlayButton, LV_ALIGN_CENTER);

    ui_NextButton = lv_imgbtn_create(ui_BottomPanel);
    lv_imgbtn_set_src(ui_NextButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_xiyi1_png, NULL);
    lv_imgbtn_set_src(ui_NextButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_xiyi2_png, NULL);
    lv_obj_set_width(ui_NextButton, 31);
    lv_obj_set_height(ui_NextButton, 31);
    lv_obj_set_x(ui_NextButton, 50);
    lv_obj_set_y(ui_NextButton, 38);
    lv_obj_set_align(ui_NextButton, LV_ALIGN_CENTER);

    ui_PlayModeButton = lv_imgbtn_create(ui_BottomPanel);
    lv_imgbtn_set_src(ui_PlayModeButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_list_loop_png, NULL);
    lv_imgbtn_set_src(ui_PlayModeButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_list_loop_png, NULL);
    lv_obj_set_width(ui_PlayModeButton, 36);
    lv_obj_set_height(ui_PlayModeButton, 31);
    lv_obj_set_x(ui_PlayModeButton, -92);
    lv_obj_set_y(ui_PlayModeButton, 36);
    lv_obj_set_align(ui_PlayModeButton, LV_ALIGN_CENTER);

    ui_VolumeButton = lv_imgbtn_create(ui_BottomPanel);
    lv_imgbtn_set_src(ui_VolumeButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_yinliang_png, NULL);
    lv_imgbtn_set_src(ui_VolumeButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_yinliang_png, NULL);
    lv_obj_set_width(ui_VolumeButton, 36);
    lv_obj_set_height(ui_VolumeButton, 31);
    lv_obj_set_x(ui_VolumeButton, 100);
    lv_obj_set_y(ui_VolumeButton, 38);
    lv_obj_set_align(ui_VolumeButton, LV_ALIGN_CENTER);

    ui_PrevButton = lv_imgbtn_create(ui_BottomPanel);
    lv_imgbtn_set_src(ui_PrevButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_shangyi1_png, NULL);
    lv_imgbtn_set_src(ui_PrevButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_shangyi2_png, NULL);
    lv_obj_set_width(ui_PrevButton, 31);
    lv_obj_set_height(ui_PrevButton, 31);
    lv_obj_set_x(ui_PrevButton, -50);
    lv_obj_set_y(ui_PrevButton, 38);
    lv_obj_set_align(ui_PrevButton, LV_ALIGN_CENTER);

    ui_MidPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_MidPanel, 240);
    lv_obj_set_height(ui_MidPanel, 165);
    lv_obj_set_x(ui_MidPanel, 0);
    lv_obj_set_y(ui_MidPanel, -48);
    lv_obj_set_align(ui_MidPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MidPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_MidPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MidPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MidPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jiaopian = lv_img_create(ui_MidPanel);
    lv_img_set_src(ui_jiaopian, &ui_img_jiaopian_png);
    lv_obj_set_width(ui_jiaopian, LV_SIZE_CONTENT);  /// 169
    lv_obj_set_height(ui_jiaopian, LV_SIZE_CONTENT); /// 164
    lv_obj_set_align(ui_jiaopian, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_jiaopian, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_jiaopian, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_haibao = lv_img_create(ui_MidPanel);
    lv_img_set_src(ui_haibao, &ui_img_haibao_png);
    lv_obj_set_width(ui_haibao, LV_SIZE_CONTENT);  /// 93
    lv_obj_set_height(ui_haibao, LV_SIZE_CONTENT); /// 93
    lv_obj_set_align(ui_haibao, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_haibao, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_haibao, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_citou = lv_img_create(ui_MidPanel);
    lv_img_set_src(ui_citou, &ui_img_citou_png);
    lv_obj_set_width(ui_citou, LV_SIZE_CONTENT);  /// 68
    lv_obj_set_height(ui_citou, LV_SIZE_CONTENT); /// 141
    lv_obj_set_x(ui_citou, 85);
    lv_obj_set_y(ui_citou, -33);
    lv_obj_set_align(ui_citou, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_citou, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_citou, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_pivot(ui_citou, 50, 28);
    lv_img_set_angle(ui_citou, -200);

    ui_TopPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_TopPanel, 240);
    lv_obj_set_height(ui_TopPanel, 25);
    lv_obj_set_align(ui_TopPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TopPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopPanel, lv_color_hex(0x021F33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_Image1, &ui_img_fanhui_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);  /// 16
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT); /// 12
    lv_obj_set_x(ui_Image1, -100);
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_ImgButton2 = lv_imgbtn_create(ui_TopPanel);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_caidan_png, NULL);
    lv_obj_set_width(ui_ImgButton2, 16);
    lv_obj_set_height(ui_ImgButton2, 17);
    lv_obj_set_x(ui_ImgButton2, 100);
    lv_obj_set_y(ui_ImgButton2, 0);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_Label2 = lv_label_create(ui_TopPanel);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "正在播放");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_HONOR_Light12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_caidanPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_caidanPanel, 148);
    lv_obj_set_height(ui_caidanPanel, 295);
    lv_obj_set_align(ui_caidanPanel, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_caidanPanel, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_caidanPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_caidanPanel, lv_color_hex(0x0D2B3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_caidanPanel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_caidanPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlayListPanel = lv_obj_create(ui_caidanPanel);
    lv_obj_set_width(ui_PlayListPanel, 148);
    lv_obj_set_height(ui_PlayListPanel, 254);
    lv_obj_set_x(ui_PlayListPanel, 2);
    lv_obj_set_y(ui_PlayListPanel, 16);
    lv_obj_set_align(ui_PlayListPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PlayListPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_scrollbar_mode(ui_PlayListPanel, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_PlayListPanel, LV_DIR_VER);
    lv_obj_set_scroll_snap_x(ui_PlayListPanel, LV_SCROLL_SNAP_START);
    lv_obj_set_style_radius(ui_PlayListPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PlayListPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlayListPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PlayListPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_caidanPanel);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -129);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "播放列表（1/100）");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_HONOR_Light12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_caidanPanel);
    lv_obj_set_width(ui_Panel1, 120);
    lv_obj_set_height(ui_Panel1, 1);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -116);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_VolumePanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_VolumePanel, 220);
    lv_obj_set_height(ui_VolumePanel, 60);
    lv_obj_set_x(ui_VolumePanel, 0);
    lv_obj_set_y(ui_VolumePanel, -52);
    lv_obj_set_align(ui_VolumePanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VolumePanel, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_VolumePanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_VolumePanel, lv_color_hex(0x102C41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumePanel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VolumePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolumeSlider = lv_slider_create(ui_VolumePanel);
    lv_slider_set_range(ui_VolumeSlider, 0, 21);
    lv_slider_set_value(ui_VolumeSlider, 15, LV_ANIM_OFF);
    if (lv_slider_get_mode(ui_VolumeSlider) == LV_SLIDER_MODE_RANGE)
        lv_slider_set_left_value(ui_VolumeSlider, 0,
                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_VolumeSlider, 170);
    lv_obj_set_height(ui_VolumeSlider, 8);
    lv_obj_set_x(ui_VolumeSlider, 0);
    lv_obj_set_y(ui_VolumeSlider, 12);
    lv_obj_set_align(ui_VolumeSlider, LV_ALIGN_CENTER);

    ui_VolumeLabel = lv_label_create(ui_VolumePanel);
    lv_obj_set_width(ui_VolumeLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_VolumeLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_VolumeLabel, -11);
    lv_obj_set_y(ui_VolumeLabel, -12);
    lv_obj_set_align(ui_VolumeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VolumeLabel, "音量：");
    lv_obj_set_style_text_color(ui_VolumeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VolumeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VolumeLabel, &ui_font_HONOR_Light12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolumeValueLabel = lv_label_create(ui_VolumePanel);
    lv_obj_set_width(ui_VolumeValueLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_VolumeValueLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_VolumeValueLabel, 8);
    lv_obj_set_y(ui_VolumeValueLabel, -12);
    lv_obj_set_align(ui_VolumeValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VolumeValueLabel, "15");
    lv_obj_set_style_text_color(ui_VolumeValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VolumeValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VolumeValueLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_background1, ui_event_background1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_background2, ui_event_background2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PauseButton, ui_event_PauseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlayButton, ui_event_PlayButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextButton, ui_event_NextButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlayModeButton, ui_event_PlayModeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VolumeButton, ui_event_VolumeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrevButton, ui_event_PrevButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BottomPanel, ui_event_BottomPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MidPanel, ui_event_MidPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VolumeSlider, ui_event_VolumeSlider, LV_EVENT_ALL, NULL);
}
